### ISSUE TITLE
hgSQLBasics missing?

### ISSUE THREAD

**Issue by riasc** [timbitz/aligater#1]
Hello,
as I'm working on something similar, so `aligater` caught my attention. I was trying to reproduce the analysis with aligater, but somehow couldn't get it to work with the default parameters. The `hgSQLBasics` module seems to be missing at it is in the `intRagenic` repository. Or what am I missing? Just piping the results from `aligater align` should be sufficient? Also I can't get any usage information on the specific aligater steps with `-h`, e.g., `aligater detect -h` but I guess thats still to come. 

Cheers.
Richard

**Comment by timbitz** [comment]
Hey Richard,
   Sorry to take so long with this.  I'm not really developing this actively at the moment and so I apologize for the lack of documentation and that missing dependency!...

As a quick fix, I added that library, even though its mostly not used.  Additionally as of #2 I have fixed the broken link to the database, and added a bit of documentation which should be sufficient to reproduce the analysis.

Please let me know if there is anything missing or unclear..

Cheers, -t
