### ISSUE TITLE
Julia Version

### ISSUE THREAD

**Issue by fgypas** [timbitz/aligater#4]
The reclassification step (aligater reclass --uniq --save database.jlz < lig/*blast.filtered.lig) works only with Julia 0.4. If you use 0.5 it will ask for 0.4. So the documentation should change to ask specifically for 0.4.

**Comment by timbitz** [comment]
Thanks for letting me know!  I have not yet added support for Julia 0.5, but plan to do so eventually.  I have updated the readme's Julia requirement in f9282f1 to reflect this.  Thanks!
