### ISSUE TITLE
Blast problem

### ISSUE THREAD

**Issue by fgypas** [timbitz/aligater#5]
Hi 

In the documentation you mention to download the following BLAST databases:
"nr, human_genomic, other_genomic"

I got an error at the post step and after searching on the code it seems that the databases that one should use is nt and not nr. More specifically on line 44 of Aligater/bin/post.pl you have the following line: my $blastDb = "human_genomic,other_genomic,nt"

Based on this should I use the nt database and not the nr?

Thank you in advance
Foivos

**Comment by timbitz** [comment]
Ahh... typo!  `nt` is the correct database.  Thank you for pointing that out!!
The typo has been corrected in 2cacac0.
