### ISSUE TITLE
Error on aligater reclass (generate database)

### ISSUE THREAD

**Issue by fgypas** [timbitz/aligater#6]
When I run the following command to generate the database:
`aligater reclass --uniq --save database.jlz < lig/*blast.filtered.lig`
I get a bash error: "ambiguous redirect."

Then I specified the files one by one like the following:
`aligater reclass --uniq --save database.jlz < lig/file1.blast.filtered.lig lig/file2.blast.filtered.lig `

But now i get another error message:
"too many arguments"

Finally I concatenated the files into one and ran aligater reclass (which worked), but I am not sure if this is a proper way of doing it.
`aligater reclass --uniq --save database.jlz < <(cat lig/*blast.filtered.lig)`

So am I allowed to concatenate all the files and then run aligater reclass?

**Comment by timbitz** [comment]
For generating the database you should just combine them with cat.  Then in the next step run each filtering step independently with that single database you generated.

**Comment by fgypas** [comment]
Great thanks a lot.
